name: Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
        echo "ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ${{secrets.USER_NAME}}@${{secrets.SSH_HOST}}
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{secrets.USER_NAME}}@${{secrets.SSH_HOST}} 
          '
              cd /home/ubuntu/nest-hello-world &&
              sudo npm run start
          '