name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            host : ${{secrets.SSH_HOST}}
            username: ${{secrets.USER_NAME}}
      
        script: |
            cd ~/nest-hello-world/
            git pull origin main
            sudo npm run build
            sudo npm run start